@startuml
'https://plantuml.com/component-diagram

component "Client_Frontend" {
    folder "views" {
        [Lobby]
        [Room]
        [Announcement]
        [Game]
        [Game finished]
    }
    component [ui-components]

    [Lobby] --> [ui-components]
    [Room] --> [ui-components]
    [Game] --> [ui-components]
    [Announcement] --> [ui-components]
    [Game] --> [ui-components]
    [Game finished] --> [ui-components]
}
note top of Client_Frontend: React components\n-Material UI\n- React Router\n-Grommet\n-Video

component [External Video chat api]

component "Server - Backend" {
    component [api]
    note right of api: implemented with spring data rest. \n spring data rest provides the controllers and services

    component [bean validation]

    component [access control]

    component [state validation]

    component [spring data rest resources]

    component [entities]

    component [JPA]

    component [event handlers for side effects]

    component [GameLogic]

    api --> [bean validation]
    api --> [access control]
    api --> [state validation]
    api --> [spring data rest resources]
    api --> [event handlers for side effects]

    [spring data rest resources] --> [entities]
    [spring data rest resources] --> [JPA]

    [access control] --> [GameLogic]
    [state validation] --> [GameLogic]
    [event handlers for side effects] --> [GameLogic]
}

database Database

Client_Frontend ..> [api]: REST
[External Video chat api] <-- Client_Frontend

[JPA] --> Database

@enduml
